ALTER TABLE vm_registrations
  ADD COLUMN IF NOT EXISTS vcpu INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS memory_gb INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS storage_gb INTEGER NOT NULL DEFAULT 0;
